[com/github/stunkymonkey/nautilus-open-any-terminal]
terminal='kitty'

[org/gnome/desktop/default-applications/terminal]
exec='kitty'
exec-arg='--'

[org/gnome/desktop/interface]
cursor-theme='phinger-cursors'
document-font-name='Cantarell 11'
font-name='Cantarell 11'
gtk-theme='Orchis-dark-ryleu'
icon-theme='Papirus-Dark'
monospace-font-name='FiraCode Nerd Font Mono 10'

[org/gnome/desktop/privacy]
disable-microphone=false
report-technical-problems=false

[org/gnome/desktop/wm/keybindings]
move-to-workspace-1=['<Primary><Shift><Alt>Home']
move-to-workspace-last=['<Primary><Shift><Alt>End']
move-to-workspace-left=['<Primary><Shift><Alt>Left']
move-to-workspace-right=['<Primary><Shift><Alt>Right']
switch-to-workspace-1=['<Primary><Alt>Home']
switch-to-workspace-last=['<Primary><Alt>End']
switch-to-workspace-left=['<Primary><Alt>Left']
switch-to-workspace-right=['<Primary><Alt>Right']

[org/gnome/desktop/wm/preferences]
button-layout='appmenu:minimize,maximize,close'
titlebar-font='Cantarell Bold 11'

[org/gnome/mutter]
edge-tiling=false

[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/open-terminal/']

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/open-terminal]
binding='<Primary><Alt>t'
command='kitty'
name='Terminal'

[org/gnome/shell]
command-history=['kitty']
disable-user-extensions=false
disabled-extensions=['background-logo@fedorahosted.org']
enabled-extensions=['appindicatorsupport@rgcjonas.gmail.com', 'blur-my-shell@aunetx', 'pop-shell@system76.com', 'user-theme@gnome-shell-extensions.gcampax.github.com']
remember-mount-password=true

[org/gnome/shell/extensions/pop-shell]
gap-inner=uint32 1
gap-outer=uint32 1
show-title=false
smart-gaps=true
tile-by-default=true

[org/gnome/shell/extensions/user-theme]
name='Orchis-dark-ryleu'

[org/gnome/shell/keybindings]
switch-to-application-1=['<Super>1']
switch-to-application-2=['<Super>2']
switch-to-application-3=['<Super>3']
switch-to-application-4=['<Super>4']
switch-to-application-5=['<Super>5']
switch-to-application-6=['<Super>6']
switch-to-application-7=['<Super>7']
switch-to-application-8=['<Super>8']
switch-to-application-9=['<Super>9']

[org/gnome/software]
first-run=false

[org/gnome/system/location]
enabled=true

[org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
custom-command='fish'
use-custom-command=true

[org/gnome/tweaks]
show-extensions-notice=false
