# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep nomatch
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
if [[ -e "$HOME/.zshrc" ]]; then
	zstyle :compinstall filename "$HOME/.zshrc"
fi

autoload -Uz compinit
compinit
# End of lines added by compinstall

EDITOR="/usr/bin/micro"

STARSHIP_CONFIG="$HOME/.config/starship/config.toml"

# fix zsh weirdness with home / end / other similar keys. i need to make a tool for this
bindkey "\e[1;5D" 		backward-word
bindkey "\e[1;5C" 		forward-word

# alt-bs and ctrl-del
bindkey "\e[3;5~"		kill-word
bindkey "\033Z"			backward-kill-word

# del, home and end
bindkey "\e[3~"			delete-char
bindkey "\033[H"		beginning-of-line
bindkey "\033[F"		end-of-line


# automatically enable python venvs. thank you, CatDevz!
function cd() {
  builtin cd "$@"

  if [[ -z "$VIRTUAL_ENV" ]] ; then
    if [[ -d ./venv ]] ; then
      source ./venv/bin/activate
    fi
  else
    parentdir="$(dirname "$VIRTUAL_ENV")"
    if [[ "$PWD"/ != "$parentdir"/* ]] ; then
      deactivate
    fi
  fi
}

# Source global definitions
if [ -f /etc/zshrc ]; then
	. /etc/zshrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
if [[ -d ~/go/bin/ ]]; then
	PATH="$PATH:$HOME/go/bin"
fi
export PATH

if [[ -f /usr/bin/eza ]]; then
	alias ls="eza --icons"
	alias la="eza -alF --icons"
fi
alias ccat="bat -pp --tabs 4"
alias whatismyip="curl -s checkip.amazonaws.com"

if [[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
	source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi
if [[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
	source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

eval $(thefuck --alias)

if [[ $(starship init zsh) != $(cat ~/.starship_zsh) ]]
then
	starship init zsh > ~/.starship_zsh
fi
source ~/.starship_zsh

if [[ -d ~/.spicetify/ ]]; then
	export PATH=$PATH:$(realpath ~/.spicetify)
fi

# bun completions
[ -s "/home/$USER/.bun/_bun" ] && source "/home/$USER/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

[ -f "/home/ryleu/.ghcup/env" ] && source "/home/ryleu/.ghcup/env"

eval "$(zoxide init --cmd cd zsh)"
